blank_issues_enabled: false
contact_links:
  - name: Dokumentation
    url: https://github.com/MasterofMakros/AI-Dataanalyzer-Researcher-/tree/main/docs
    about: Lies zuerst die Dokumentation
  - name: Diskussionen
    url: https://github.com/MasterofMakros/AI-Dataanalyzer-Researcher-/discussions
    about: Fragen und Diskussionen
