use_default_settings: true
server:
  secret_key: "change-this-key-to-something-random"
  limiter: false
  public_instance: false
  method: "GET"
  port: 8080
  bind_address: "0.0.0.0"

ui:
  static_use_hash: true

search:
  safe_search: 0
  autocomplete: "google"
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: true

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: true

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: true
